<a href="https://colab.research.google.com/github/Yubraj45/Numpy-projects/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import test
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [ ]:
print(train['Survived'].value_counts(normalize=True))

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [ ]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
print("\nColumns in train:", train.columns.tolist())

Columns in train: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [ ]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
train_clean= train.copy()
test_clean= test.copy()
train_clean['Age'] = train_clean.groupby(['Pclass', 'Sex'])['Age'].transform(lambda x: x.fillna(x.median()))
test_clean['Age']= test_clean.groupby(['Pclass', 'Sex'])['Age'].transform(lambda x: x.fillna(x.median()))

In [ ]:
train_clean

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.5,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
train_clean.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
train_clean['Embarked']= train_clean['Embarked'].fillna(train_clean['Embarked'].mode()[0])

In [ ]:
test_clean['Fare']= test_clean['Fare'].fillna(test_clean['Fare'].median())

In [ ]:
test_clean.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [ ]:
train_clean['Has_Cabin']= train_clean['Cabin'].notnull().astype(int)
test_clean['Has_Cabin']= test_clean['Cabin'].notnull().astype(int)

In [ ]:
train_clean['Deck'] = train_clean['Cabin'].str[0]
test_clean['Deck'] = test_clean['Cabin'].str[0]

In [ ]:
train_clean['Deck'] = train_clean['Deck'].fillna('U')
test_clean['Deck'] = test_clean['Deck'].fillna('U')

In [ ]:
train_clean.drop('Cabin', axis=1, inplace=True)
test_clean.drop('Cabin', axis=1, inplace=True)

In [ ]:
train_clean['Title']= train_clean['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
test_clean['Title']= test_clean['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_2531/942210227.py:1: SyntaxWarning: invalid escape sequence '\.'
  train_clean['Title']= train_clean['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
/tmp/ipykernel_2531/942210227.py:2: SyntaxWarning: invalid escape sequence '\.'
  test_clean['Title']= test_clean['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

In [ ]:
rare_titles = ['Lady', 'Countess', 'Capt', 'Col', 'Don', 'Dr', 'Major',
               'Rev', 'Sir', 'Jonkheer', 'Dona']

In [ ]:
train_clean['Title']= train_clean['Title'].replace(rare_titles, 'Rare')
test_clean['Title']= test_clean['Title'].replace(rare_titles, 'Rare')

In [ ]:
#CLEAN SOME TITLES
train_clean['Title'] = train_clean['Title'].replace(['Mlle', 'Ms'], 'Miss')
train_clean['Title'] = train_clean['Title'].replace('Mme', 'Mrs')

test_clean['Title'] = test_clean['Title'].replace(['Mlle', 'Ms'], 'Miss')
test_clean['Title'] = test_clean['Title'].replace('Mme', 'Mrs')

In [ ]:
#FAMILY SIZE
train_clean['FamilySize']= train_clean['Parch'] + train_clean['SibSp'] + 1
test_clean['FamilySize']= test_clean['Parch'] + test_clean['SibSp'] + 1

In [ ]:
train_clean['IsAlone']= (train_clean['FamilySize']==1).astype(int)
test_clean['IsAlone']= (test_clean['FamilySize']==1).astype(int)

In [ ]:
train_clean.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Has_Cabin      0
Deck           0
Title          0
FamilySize     0
IsAlone        0
dtype: int64

In [ ]:
test_clean.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Has_Cabin      0
Deck           0
Title          0
FamilySize     0
IsAlone        0
dtype: int64

In [ ]:
train_clean['Sex']= train_clean['Sex'].map({'male':0, 'female':1})
test_clean['Sex']= test_clean['Sex'].map({'male':0, 'female':1})

train_clean= pd.get_dummies(train_clean, columns=['Embarked', 'Title', 'Deck'], drop_first=True)
test_clean= pd.get_dummies(test_clean, columns=['Embarked', 'Title', 'Deck'], drop_first=True)

In [ ]:
train_clean[train_clean.select_dtypes(include='bool').columns]= train_clean.select_dtypes(include='bool').astype(int)
test_clean[test_clean.select_dtypes(include='bool').columns]= test_clean.select_dtypes(include='bool').astype(int)

In [ ]:
train_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Has_Cabin    891 non-null    int64
 11  FamilySize   891 non-null    int64
 12  IsAlone      891 non-null    int64
 13  Embarked_Q   891 non-null    int64
 14  Embarked_S   891 non-null    int64
 15  Title_Miss   891 non-null    int64
 16  Title_Mr     891 non-null    int64
 17  Title_Mrs    891 non-null    int64
 18  Title_Rare   891 non-null    int64
 19  Deck_B       891 non-null    int64
 20  Deck_C       891 non-null    int64
 21  Deck_D       891 non-null    int64
 22  Deck_E       891 non-null    int64
 23  Deck_F       891 non-null    int64
 24  Deck_G       891 non-null    int64
 25  Deck_T       891 non-null    int64
 26  Deck_U       891 non-null    int64
dtypes: float64(2), int64(23), object(2)
memory usage: 188.1+ KB

In [ ]:
num_features = ['Age', 'Fare', 'FamilySize', 'SibSp', 'Parch']
cat_features= ['Pclass', 'Sex', 'Embarked', 'Title', 'Deck', 'Has_Cabin', 'IsAlone']

In [ ]:
X= train_clean.drop(columns=['Survived', 'PassengerId', 'Name', 'Ticket'])
y= train_clean['Survived']

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      891 non-null    int64
 1   Sex         891 non-null    int64
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Has_Cabin   891 non-null    int64
 7   FamilySize  891 non-null    int64
 8   IsAlone     891 non-null    int64
 9   Embarked_Q  891 non-null    int64
 10  Embarked_S  891 non-null    int64
 11  Title_Miss  891 non-null    int64
 12  Title_Mr    891 non-null    int64
 13  Title_Mrs   891 non-null    int64
 14  Title_Rare  891 non-null    int64
 15  Deck_B      891 non-null    int64
 16  Deck_C      891 non-null    int64
 17  Deck_D      891 non-null    int64
 18  Deck_E      891 non-null    int64
 19  Deck_F      891 non-null    int64
 20  Deck_G      891 non-null    int64
 21  Deck_T      891 non-null    int64
 22  Deck_U      891 non-null    int64
dtypes: float64(2), int64(21)
memory usage: 160.2 KB

In [ ]:
#PREPROCESSING PIPELINE


# USING RANDOMFOREST CLASSIFIER
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, y , random_state=42)

# rfc= RandomForestClassifier(n_estimators=100, random_state=42)
# rfc.fit(X_train, y_train)
# y_pred= rfc.predict(X_test)
# from sklearn.metrics import accuracy_score
# accuracy_score(y_test, y_pred)

0.8026905829596412

In [ ]:
# LOGISTIC REGRESSION
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, y , random_state=42)
# lr= LogisticRegression(random_state=42)
# lr.fit(X_train, y_train)

# y_pred= lr.predict(X_test)
# from sklearn.metrics import accuracy_score
# accuracy_score( y_pred, y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8116591928251121